### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by conradwt** [swiftlang/swift-docker#278]
I'm getting the following message when I attempt to pull the Swift Docker image:

```zsh
➜ docker pull swift
Using default tag: latest
latest: Pulling from library/swift
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I'm using the following:

- Apple M1 Max 15" MacBook Pro
- macOS 12.3.1
- Xcode 13.3.1

Finally, my goal here is to run everything natively on Apple Silicon.

**Comment by alexanderpuchta** [comment]
same here, anyone found a workaround for this already?

**Comment by CypherPoet** [comment]
I'm not sure if it's the best solution for every use case -- let alone a permanent one -- but I switched to manually specifying `swift:5.6-focal` and haven't had issues. 

```sh
docker pull swift:5.6-focal
```

Perhaps there's some delay?... or the `latest` image itself is missing some kind of platform specification? Not quite sure 🤔

**Comment by yosifkit** [comment]
Just to note what the problem was: when this issue was opened, the `latest` tag did not specify support for `arm64v8`, so it was not built in Docker Official Images. See the `library/swift` file and note that no architectures are specified, so the default of `amd64` would be used: https://github.com/docker-library/official-images/pull/12215/files#diff-7077506a2e33dccfe04067c214e487097a88497efd08c9ffcfb573f04e1bd86cL10-R12

But `arm64v8` was added in September 2022 via https://github.com/docker-library/official-images/pull/13145 so this issue can be closed.

**Comment by conradwt** [comment]
@yosifkit Yes, things are working as expected now. Thus, I'm going to close this issue.
