### ISSUE TITLE
container gets stuck restarting when using docker-compose

### ISSUE THREAD

**Issue by arielelkin** [swiftlang/swift-docker#64]
**docker-compose.yml**

```
version: '3'

services:
  server:
    image: swift:3.0
    volumes:
      - ./:/files/
    ports:
      - 80:80
    restart: always
```

```
$ docker-compose up
Creating mydirectory_server_1
Attaching to mydirectory_server_1
mydirectory_server_1 exited with code 0

$ docker-compose ps
      Name          Command      State      Ports 
-------------------------------------------------
mydirectory_server_1   /bin/bash   Restarting 
```

Pretty confusing... Why is it stuck restarting?

**Comment by arielelkin** [comment]
@hamin @swizzlr bump 🙂

**Comment by swizzlr** [comment]
@arielelkin Sorry for the delay in getting back to you on this.

So, what you have here is an infinite restart loop because the default command for Swift is `bash`. You need to specify what you want your container to do on start (https://docs.docker.com/compose/compose-file/#/command)

```yaml
command: swift build && .build/debug/Server
```

Although if your compilation times are long, you may want to create your own Swift image first by writing a Dockerfile.
